--DROP TABLE coffeemachine;
--DROP TABLE coffee;

CREATE TABLE IF NOT EXISTS coffee
(
    coffee_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    coffee_name   VARCHAR(512)                            NOT NULL,
    milk_volume   BIGINT,
    coffee_volume BIGINT                                  NOT NULL,
    CONSTRAINT pk_coffee PRIMARY KEY (coffee_id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (coffee_name)
);

CREATE TABLE IF NOT EXISTS coffeemachine
(
    coffemechine_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    coffemechine_name VARCHAR(512)                            NOT NULL,
    coffee_id         BIGINT                                  NOT NULL,
    power             BOOLEAN                                 NOT NULL DEFAULT 'false',
    CONSTRAINT pk_coffeemachine PRIMARY KEY (coffemechine_id),
    CONSTRAINT fk_coffee FOREIGN KEY (coffee_id) REFERENCES coffee (coffee_id)
);