
DROP TABLE coffee_make;
DROP TABLE coffee_machine;
DROP TABLE coffee;

CREATE TABLE IF NOT EXISTS coffee
(
    coffee_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    coffee_name   VARCHAR(512)                            NOT NULL,
    milk_volume   BIGINT,
    coffee_volume BIGINT                                  NOT NULL,
    CONSTRAINT pk_coffee PRIMARY KEY (coffee_id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (coffee_name)
);

CREATE TABLE IF NOT EXISTS coffee_machine
(
    coffee_machine_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    coffee_machine_name VARCHAR(512)                            NOT NULL,
    power               BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_coffee_machine PRIMARY KEY (coffee_machine_id)
);

CREATE TABLE IF NOT EXISTS coffee_make
(
    coffee_make_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    coffee_machine_id BIGINT NOT NULL,
    coffee_id         BIGINT NOT NULL,
    CONSTRAINT pk_coffee_make PRIMARY KEY (coffee_make_id),
    CONSTRAINT fk_role_id_users_roles FOREIGN KEY (coffee_machine_id) REFERENCES coffee_machine (coffee_machine_id),
    CONSTRAINT fk_user_id_users_roles FOREIGN KEY (coffee_id) REFERENCES coffee (coffee_id)
);